# Generated by Django 5.1.4 on 2026-03-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('dns_category_slug', models.CharField(blank=True, default='', max_length=255, verbose_name='Slug категории в DNS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Слаг')),
                ('vendor_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Артикул')),
                ('url', models.URLField(max_length=1024, verbose_name='URL на DNS')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-last_parsed_at'],
            },
        ),
    ]
