# Generated by Django 5.1.4 on 2026-05-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_embedding_e5_768'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='offer_source_mpn_idx',
        ),
    ]
