# Generated by Django 5.1.4 on 2026-05-19 21:18

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_citilink_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_key_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Хэш варианта внутри семьи'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Specs, отличающие данный вариант внутри семьи (ram_gb, storage_gb, color).', verbose_name='Характеристики варианта'),
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=512, verbose_name='Название семейства')),
                ('brand', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Бренд')),
                ('model_code', models.CharField(blank=True, default='', help_text='Канонический код модели без указания поколения (например, "X1 Carbon").', max_length=128, verbose_name='Модельный код')),
                ('generation', models.CharField(blank=True, default='', help_text='Поколение/ревизия модели (например, "Gen 11", "M3").', max_length=64, verbose_name='Поколение')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('common_specs', models.JSONField(blank=True, default=dict, help_text='Specs, общие для всех вариантов семьи (cpu_family, gpu_family, screen_in и т. п.).', verbose_name='Общие характеристики')),
                ('family_key_hash', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Хэш семейного ключа')),
                ('match_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Вектор по «семейному» названию без варьируемых полей.', null=True, verbose_name='Embedding для матчинга семьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Семейство товаров',
                'verbose_name_plural': 'Семейства товаров',
                'ordering': ['brand', 'model_code', 'generation'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.productfamily', verbose_name='Семейство'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['family', 'variant_key_hash'], name='products_pr_family__cffbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['brand', 'category'], name='products_pr_brand_7142ad_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['family_key_hash'], name='products_pr_family__ee0552_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=django.contrib.postgres.indexes.GinIndex(fields=['common_specs'], name='family_common_specs_gin'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['match_embedding'], m=16, name='family_match_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
