# Generated by Django 5.1.4 on 2026-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_categorylisting_source_alter_offer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='extra_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Поля специфичные для источника: rating, reviews_count, brand, brand_id, sale_percent, cashback_percent, supplier и т.д.', verbose_name='Доп. метаданные источника'),
        ),
    ]
