# Generated by Django 5.1.4 on 2026-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_offer_extra_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylisting',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('citilink', 'Ситилинк'), ('ozon', 'Ozon'), ('wb', 'Wildberries'), ('regard', 'Регард')], db_index=True, max_length=32, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries'), ('regard', 'Регард')], db_index=True, max_length=32, verbose_name='Магазин'),
        ),
    ]
