# Generated by Django 5.1.4 on 2026-05-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_categorylisting_source_alter_offer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='current_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Актуальная цена до скидки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Актуальная цена'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Цена обновлена'),
        ),
    ]
