# Generated by Django 5.1.4 on 2026-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_backfill_offer_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylisting',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('citilink', 'Ситилинк'), ('ozon', 'Ozon'), ('wb', 'Wildberries'), ('regard', 'Регард'), ('mvideo', 'М.Видео')], db_index=True, max_length=32, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries'), ('regard', 'Регард'), ('mvideo', 'М.Видео')], db_index=True, max_length=32, verbose_name='Магазин'),
        ),
    ]
