# Generated by Django 5.1.4 on 2026-05-31 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_wishlist_wishlistitem'),
        ('products', '0022_alter_categorylisting_source_alter_offer_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('price_drop', 'Падение цены'), ('anomaly', 'Аномалия'), ('availability', 'Появление в наличии'), ('info', 'Информация')], db_index=True, default='price_drop', max_length=16, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notify_on',
            field=models.CharField(choices=[('price_drop', 'Падение цены'), ('anomaly', 'Аномалия'), ('availability', 'Появление в наличии')], default='price_drop', max_length=16, verbose_name='Условие уведомления'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='alerts_noti_user_id_0041fd_idx'),
        ),
    ]
