/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Cabinet Grotesk"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        scout: {
          bg:        '#0A0A0A',
          elevated:  '#141414',
          subtle:    '#1C1C1C',
          hover:     '#262626',
          border:    '#2E2E2E',
          'border-soft': '#1C1C1C',
          text:      '#F5F5F5',
          muted:     '#A3A3A3',
          dim:       '#666666',
          accent:    '#A855F7',
          'accent-hover': '#9333EA',
          success:   '#10B981',
          warning:   '#F59E0B',
          danger:    '#EF4444',
        },
        steam: {
          bg:      '#1b2838',
          darker:  '#16202d',
          card:    '#171a21',
          panel:   '#1f2a3a',
          border:  '#2a3f5a',
          blue:    '#66c0f4',
          link:    '#67c1f5',
          light:   '#c7d5e0',
          text:    '#c7d5e0',
          muted:   '#8f98a0',
          dim:     '#67707b',
          green:   '#a4d007',
          greenHi: '#b9e02e',
          orange:  '#dba84e',
          yellow:  '#dba84e',
        },
        brand: {
          50:  '#e8f4fb',
          100: '#cfeafa',
          200: '#a5d8f5',
          300: '#67c1f5',
          400: '#66c0f4',
          500: '#3a98d6',
          600: '#2f7eb3',
          700: '#256590',
          800: '#1c4d6d',
          900: '#16202d',
          950: '#0e1620',
        },
      },
      borderRadius: {
        steam: '2px',
        'steam-lg': '4px',
        scout: '4px',
        'scout-lg': '6px',
        'scout-xl': '8px',
      },
      letterSpacing: {
        'scout-tight': '-0.035em',
        'scout-display': '-0.03em',
        'scout-h3': '-0.02em',
        'scout-caption': '0.12em',
      },
      transitionTimingFunction: {
        scout: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.15s linear',
        'scout-rise': 'scoutRise 600ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'scout-fade': 'fadeIn 200ms ease-out both',
        'scout-slide-in': 'scoutSlideIn 240ms cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scoutRise: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scoutSlideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
