# Generated by Django 5.1.4 on 2026-03-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена (до скидки)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время фиксации')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальна')),
                ('source', models.CharField(choices=[('dns', 'DNS')], default='dns', max_length=50, verbose_name='Источник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запись цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', '-timestamp'], name='prices_pric_product_5d92d3_idx')],
            },
        ),
    ]
