# Generated by Django 5.1.4 on 2026-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon')], default='dns', max_length=50, verbose_name='Источник'),
        ),
    ]
