# Generated by Django 5.1.4 on 2026-05-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_timescaledb_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserun',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries')], db_index=True, max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries')], default='dns', max_length=50, verbose_name='Источник'),
        ),
    ]
