# Generated by Django 5.1.4 on 2026-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_alter_parserun_source_alter_pricehistory_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserun',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries'), ('regard', 'Регард'), ('mvideo', 'М.Видео')], db_index=True, max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('dns', 'DNS'), ('ozon', 'Ozon'), ('citilink', 'Ситилинк'), ('wb', 'Wildberries'), ('regard', 'Регард'), ('mvideo', 'М.Видео')], default='dns', max_length=50, verbose_name='Источник'),
        ),
    ]
