# Generated by Django 5.1.4 on 2026-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Согласие с условиями'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие принято'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_telegram',
            field=models.BooleanField(default=False, verbose_name='Дублировать уведомления в Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Telegram chat_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Код привязки Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код привязки истекает'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram привязан'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Telegram username'),
        ),
    ]
