# Generated by Django 5.1.4 on 2026-05-31 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0022_alter_categorylisting_source_alter_offer_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(default='Моя сборка', max_length=255, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сборка ПК',
                'verbose_name_plural': 'Сборки ПК',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slot', models.CharField(choices=[('cpu', 'Процессор'), ('mb', 'Материнская плата'), ('gpu', 'Видеокарта'), ('ram', 'Оперативная память'), ('psu', 'Блок питания'), ('case', 'Корпус'), ('ssd', 'SSD'), ('hdd', 'Жёсткий диск')], max_length=8, verbose_name='Слот')),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена при добавлении')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='builds.build', verbose_name='Сборка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Компонент сборки',
                'verbose_name_plural': 'Компоненты сборки',
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('build', 'slot'), name='build_slot_unique')],
            },
        ),
    ]
