# Generated by Django 5.1.4 on 2026-03-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Обнаружена')),
                ('anomaly_type', models.CharField(choices=[('spike', 'Резкий скачок'), ('manipulation', 'Манипуляция (подъём перед скидкой)'), ('cyclic', 'Циклическое колебание')], max_length=50, verbose_name='Тип аномалии')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Серьёзность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('resolved', models.BooleanField(default=False, verbose_name='Разрешена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аномалия',
                'verbose_name_plural': 'Аномалии',
                'ordering': ['-detected_at'],
            },
        ),
    ]
