# Generated by Django 5.1.4 on 2026-04-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('currency_code', models.CharField(choices=[('USD', 'Доллар США'), ('EUR', 'Евро'), ('CNY', 'Юань')], default='USD', max_length=3, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс к рублю')),
                ('date', models.DateField(db_index=True, verbose_name='Дата курса')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
                'unique_together': {('currency_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('forecast_date', models.DateField(verbose_name='Дата прогноза')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прогнозная цена')),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Нижняя граница')),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Верхняя граница')),
                ('method', models.CharField(default='ARIMA', max_length=50, verbose_name='Метод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Прогноз цены',
                'verbose_name_plural': 'Прогнозы цен',
                'ordering': ['product', 'forecast_date'],
                'unique_together': {('product', 'forecast_date', 'method')},
            },
        ),
    ]
