# Generated by Django 5.1.4 on 2026-04-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_currencyrate_priceforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('full_dashboard', 'Полный дашборд'), ('clusters', 'Кластеры'), ('category_index', 'Индекс по категориям'), ('parsing_metrics', 'Метрики парсинга'), ('deals_top', 'Топ выгодных'), ('anomalies_summary', 'Сводка по аномалиям'), ('heatmap', 'Тепловая карта'), ('sensitivity', 'Чувствительность к валюте')], db_index=True, max_length=40, verbose_name='Тип снимка')),
                ('scope_key', models.CharField(blank=True, default='', help_text='Например slug категории или пусто для «все».', max_length=200, verbose_name='Область')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры расчёта')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Числа для списков и виджетов без разворачивания payload.', verbose_name='Краткая сводка')),
                ('payload', models.JSONField(default=dict, verbose_name='Полные данные')),
            ],
            options={
                'verbose_name': 'Снимок аналитики',
                'verbose_name_plural': 'Снимки аналитики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='analytics_a_kind_7e927e_idx')],
            },
        ),
    ]
