# Generated by Django 5.1.4 on 2026-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticssnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='product',
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.AlterUniqueTogether(
            name='priceforecast',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='priceforecast',
            name='product',
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='kind',
            field=models.CharField(choices=[('full_dashboard', 'Полный дашборд'), ('clusters', 'Кластеры'), ('category_index', 'Индекс по категориям'), ('parsing_metrics', 'Метрики парсинга'), ('deals_top', 'Топ выгодных'), ('heatmap', 'Тепловая карта')], db_index=True, max_length=40, verbose_name='Тип снимка'),
        ),
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.DeleteModel(
            name='PriceForecast',
        ),
    ]
